modLoader="javafml"
loaderVersion="[36,)"
logoFile="HellasHelper.png"
license="Restricted"

[[mods]]
modId="hellashelper"
version="1.0.0"
displayName="HellasHelper"
displayURL="https://discord.pixelmon-server.com"
credits="xSasaki_Haise"
authors="xSasaki_Haise"
description='''
Welcome to Hellas :)
'''

[[dependencies.hellashelper]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellashelper]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,)"
ordering="NONE"
side="BOTH"

[[dependencies.hellashelper]]
modId="hellascontrol"
mandatory=true
versionRange="[2.0.0,)"
ordering="NONE"
side="BOTH"
